### ISSUE TITLE
TODO: Scaffolding Tooling Migration

### ISSUE THREAD

**Issue by arivera12** [arivera12/OneLine#3]
- [x]  Fix dl, dt, dd in template generation
- [x] Fix form highlight trigger bug
- [x] Support for label sizing on tool
- [x] Client Side Files Management
- [x] Set properties model to be always Enumerable for UserBlobs
- [x] ~~Hide dropozone on tablet and mobile~~ (Dropzone is now clickable)
- [x] Integrate dropzone in tool
- [x] Integration of BlobData collection before and after save
- [x] On File Input Component.
  - [x] Add Minimun and Maximun allowed files parameters
  - [x] Add Minimun and Maximun allowed files reached callbacks parameters
  - [x] Add max file size parameter
  - [x] Validate max allowed files on read file operation
  - [x] Validate max file size on read file operation
  - [x] Add informative labeling
- [x] Add BlobData Validation Rules Shared
  - [x] ~~Add Validation rules before save operation and match rules using tuples~~
    - [x] Create a Pair class for mutable types, tuples are inmutable
  - [x] Integrate shared file rules validation on server and client side
- [x] Server side Fix Blob Storage Service Provider
  - [x] Implement default class for Blob Storage Service Provider
- [x] Refactor Add and Update User Blobs
  - [x] Add method without save db context
  - [x] Update method without save db context
  - [x] Delete method without save db context
- [x] Test blobs management integration
  - [x] Single
  - [x] Multiple
- [x] Implement InitialAutoSearch option 
- [x] Fix Load method
- [x] Implement or Integrate Vendor Auto Complete Component
  - [x] ~~Select Like (Single and Multiple)~~
  - [x] ~~Auto Complete Like (Single and Multiple)~~
  - [x] Implement case 1-1
  - [x] Fix AutoLoading selected value/s
- [x] Integrate Auto Complete Component in tool
- [x] Test Auto Complete Component integration
- [x] Fix Search Query
- [x] Fix Duplicates
