### ISSUE TITLE
TODO: Finish Basics Users Management

### ISSUE THREAD

**Issue by arivera12** [arivera12/OneLine#4]
**Admin**

***Backend***
- [x] Users List
- [x] Lock and unlock account
- [x] Create users account
  - [x] Roles and Permissions
- [x] Update users account
  - [x] Roles and Permissions
- [x] Change a user password
- [x] Merge AspNetUser Controller and Repository
- [x] Add Roles Controller and Repository

***Service***
- [x] Users List
- [x] Lock and unlock account
- [x] Create users account
  - [x] Roles and Permissions
- [x] Update users account
  - [x] Roles and Permissions
- [x] Change a user password
- [x] Add Roles Service

***Frontend***
- [x] Roles CRUD
  - [x] Add normalized role and concurrency stamp in repository
- [x] Users List
- [x] Create users account
  - [x] Add Roles and Permissions list
- [x] Update users account
  - [x] Add Roles and Permissions list
- [x] Change a user password (Options Modal)
- [x] Lock and unlock account (Options Modal)
